apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: noprod-child-sealed-secrets-config
  namespace: openshift-gitops
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            env: noprod
  template:
    metadata:
      name: "{{name}}-sealed-secrets-config"
    spec:
      project: default
      source:
        repoURL: https://github.com/lfalero14/gitops-middleware-operator-config.git
        targetRevision: HEAD
        path: "./manifests/middleware-sealed-secrets/overlays/noprod"
      destination:
        server: "{{server}}"
        namespace: "kube-system"
      #syncPolicy:
      #  automated:
      #  prune: true
      #  selfHeal: true
      #  allowEmpty: false
