apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: noprod-child-3scale-config
  namespace: openshift-gitops
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  env: noprod
          - list:
              elements:
                - namespace: 3scale
                - namespace: 3scale-tenant-dev
                - namespace: 3scale-tenant-testing
  template:
    metadata:
      name: "{{name}}-{{namespace}}-config"
    spec:
      project: default
      source:
        repoURL: https://github.com/lfalero14/gitops-middleware-3scale-config.git
        targetRevision: develop
        path: "./overlays/noprod/{{namespace}}"
        kustomize:
          patches:
            - target:
                kind: APIManager
                name: apimanager
              patch: |-
                - op: add
                  path: /spec/wildcardDomain
                  value: "{{metadata.labels.cluster-domain}}"
            - target:
                kind: Tenant
                name: 3scale-dev
              patch: |-
                - op: add
                  path: /spec/systemMasterUrl
                  value: "https://master.{{metadata.labels.cluster-domain}}"
            - target:
                kind: Tenant
                name: 3scale-testing
              patch: |-
                - op: add
                  path: /spec/systemMasterUrl
                  value: "https://master.{{metadata.labels.cluster-domain}}"
      destination:
        server: "{{server}}"
        namespace: "{{namespace}}"
      #syncPolicy:
      # automated:
      #   prune: true
      #   selfHeal: true
