apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: noprod-child-3scale-app-dev
  namespace: openshift-gitops
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            env: noprod
  template:
    metadata:
      name: "{{name}}-3scale-app-dev"
    spec:
      project: default
      source:
        repoURL: https://github.com/lfalero14/gitops-middleware-3scale-app.git
        targetRevision: HEAD
        path: "./overlays/noprod/dev"
      destination:
        server: "{{server}}"
        namespace: "3scale"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
