apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: noprod-child-3scale-config
  namespace: openshift-gitops
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            env: noprod
  template:
    metadata:
      name: "{{name}}-3scale-config"
    spec:
      project: default
      source:
        repoURL: https://github.com/lfalero14/gitops-middleware-3scale-config.git
        targetRevision: HEAD
        path: "./overlays/noprod"
        kustomize:
          patches:
            - target:
                kind: APIManager
                name: apimanager
              patch: |-
                - op: add
                  path: /spec/wildcardDomain
                  value: "{{metadata.labels.cluster-domain}}"
            - target:
                kind: Tenant
                name: 3scale-dev
              patch: |-
                - op: add
                  path: /spec/systemMasterUrl
                  value: "https://master.{{metadata.labels.cluster-domain}}"
            - target:
                kind: Tenant
                name: 3scale-uat
              patch: |-
                - op: add
                  path: /spec/systemMasterUrl
                  value: "https://master.{{metadata.labels.cluster-domain}}"
            - target:
                kind: Secret
                name: dev-tenant-secret
              patch: |-
                - op: add
                  path: /stringData/adminURL
                  value: "https://3scale-dev-admin.{{metadata.labels.cluster-domain}}:443"
            - target:
                kind: Secret
                name: uat-tenant-secret
              patch: |-
                - op: add
                  path: /stringData/adminURL
                  value: "https://3scale-uat-admin.{{metadata.labels.cluster-domain}}:443"
      destination:
        server: "{{server}}"
        namespace: "3scale"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
