apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tempostack-traces-testing-write
  annotations:
    argocd.argoproj.io/sync-wave: "0"
rules:
  - apiGroups: ["tempo.grafana.com"]
    resources: ["testing"]
    resourceNames: ["traces"]
    verbs: ["create"]
