---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-db-secret
  namespace: keycloak
spec:
  encryptedData:
    password: AgBUYxlcls+pWSmgSjYvUNnV5+FogLc1hEIvtnqHQTH9RwsF9QCd9BxlSZehDzduMcKZnPK/+RJjm7zFyupX9eQmsJJnULnMZe8v0AtWTddYnDFnQbufTt0vWXbfKp4vJ+gmNS2yJgWS/CZq6Nvv+vKjPYWUONpL6B++U92Z+t85XO//JNRH8TxxI/+luljcnYZuDlrJ6xEFcHXLlJDEylll6XkblUKwNPG89p2y0bGtJXFNIW7ET5//6ycV1krHjdnMsg+E8WoTKg/t5l28WRtoEAYEdvrzsmMwUYspd6j2nd75Ojvt+gzNIhRMzj5ZTeSw2wBH+y6e2c7dFPe5H8vO97Yg3ytNzOpBAbK4yY90sNlLpEZqHzOtEewSW7e3dlnLAflGlLCCUH7GU5UWdpiN0Ji93h/17OB/UlcPRKxQ6P7tym234tlRdvhpIh4CqpQJpPOa6kZcDrAmvJDGqvDtwGGh/5+er45nVrLeXRPYjvLm8NAc639TuMmQmRVIhKfKDOO7G/sONktfp8bRSWEmiJK80yK0Me5+Vd1NliCX0SFLTMoJxV2DnrRmxlaVJDUImf7iPdaEPFivu+JO5N4hIMgwRS06zNA2x5Sk9X+CeMMaiWECjHbmrWWd3yW5NCg7Xbf3MljAlljRstBK2NFG+7f5cwSzQZNAaIRXjDJiuttEuUNvY7BnrOO86UG9fqDZAPizwho=
    username: AgBRVC0YF+YygiM/HbuuIeeiRrccVp6q+QqdfamQDG9CKHxMjhpttkXciwjROcocNlY/cBpLzOzxXIgff4jMJx9SNFRGOVU4s2hVPjlOntsVqlo+acxpb+bMqRtDvPF9OPXnD0zebDIq1+SQozyC8Ikd+6/cgGrfPGcMvFRSOOe3X9m9npMT/Wq78B+lelnj8nyCD4mRHk979R9LeAeAEkAmHGDfoHspZhuUFMqLTeRYqINJXjJUZKejPWRa2PvAYVmbCcjMYIKfUhT38Vn8flYEkV8lwSZ8pDU+gticgAgz1QcWUzTklBHEOl0OtAqWq0BxqwiKYX9BJ2QrInW49jGxM93VXD+UU6aZR99zoj6hC1CLjdPUb1rnO+Cu1hBFa9HsRO3ZTvTMR3yUCPJXJaN52JByNWNP+G17Mmlk2SuJ6zHQfu9EntOV49+92nmXqyAJ/+Aq0oqTig2o0o/n3C4w/c8N/y/MhPSz5QKl5GQ8dCBI6KRhwFFf+nwHSlNm2p3XJMoTR5Dfwtb+bjXjBx6C7HTwQsFaRfu1eL+i/c9dOT+KJY/0hJYg9Spo9vRy5JEKIS6FMg5KHdkRJ47/xoYdlLrIlUDI0EPbj0M2Ehy3P13HliGJFlArVXhPVEj4gNob/ZEqRRrtFVcXm8eLe0m5wZE/Ll2TFyf41DgbpMEGkGqeNyvgYmWMYvwaxpecOtCx33kL5r6EGbQkW7N7
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
        argocd.argoproj.io/sync-wave: "0"
      creationTimestamp: null
      name: keycloak-db-secret
      namespace: keycloak
    type: Opaque
