apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    name: sealed-secrets-controller-metrics
  name: sealed-secrets-controller-metrics
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    name: sealed-secrets-controller
  type: ClusterIP
