apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - development/otel-collector_sa.yaml
  - development/write_role.yaml
  - development/write_role-binding.yaml
  - development/open-telemetry.yaml
  - testing/otel-collector_sa.yaml
  - testing/write_role.yaml
  - testing/write_role-binding.yaml
  - testing/open-telemetry.yaml
