apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  mode: deployment
  managementState: managed
  serviceAccount: otel-collector

  observability:
    metrics:
      enableMetrics: true

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/infra
                operator: In
                values:
                  - ""

  config:
    extensions:
      bearertokenauth:
        filename: "/var/run/secrets/kubernetes.io/serviceaccount/token"

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    #processors:
    #  batch: {}
    #  memory_limiter:
    #    check_interval: 1s
    #    spike_limit_percentage: 30
    #    limit_percentage: 50

    exporters:
      debug:
        verbosity: detailed
      otlp/development:
        endpoint: tempo-simplest-gateway.openshift-tempo-operator.svc.cluster.local:8090
        tls:
          insecure: false
          ca_file: "/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt"
        auth:
          authenticator: bearertokenauth
        headers:
          X-Scope-OrgID: "development"

      otlp/testing:
        endpoint: tempo-simplest-gateway.openshift-tempo-operator.svc.cluster.local:8090
        tls:
          insecure: false
          ca_file: "/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt"
        auth:
          authenticator: bearertokenauth
        headers:
          X-Scope-OrgID: "testing"

    service:
      extensions: [bearertokenauth]
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [debug, otlp/development, otlp/testing]
