apiVersion: observability.openshift.io/v1alpha1
kind: UIPlugin
metadata:
  name: distributed-tracing
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  type: DistributedTracing
  distributedTracing:
    timeout: 10s
