apiVersion: v1
kind: Secret
metadata:
  name: logging-loki-s3
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  access_key_id: "minio"
  access_key_secret: "minio123"
  bucketnames: "loki-bucket"
  endpoint: "http://minio-service.database.svc.cluster.local:9000"
